### ISSUE TITLE
Papa Johnny Bug

### ISSUE THREAD

**Issue by abhisekp** [richgilbank/Scratch-JS#81] opened 2016-03-24 06:10 UTC
**Run the following code using any compiler in the settings**

```js
const longStr = 'Johnny Johnny, yes papa';
const name = longStr.match(/(Johnny)/g);
console.log(name[0]);
console.log(name[1]);
console.log(name);
console.log(typeof name);
```

### Using browser JavaScript,
> #### Output
```js
Johnny
Johnny
["Johnny", "Johnny"]
object
```

### Using Babel or Traceur compiler 
> #### Output :bug:
```js
J
o
Johnny,Johnny
string
```

**Comment by r-murphy** [comment] 2016-05-13 14:54
I took a look at this (catchy title) and it seems to be caused by DevTools' variable scoping, and not due to the transformer or the regexp. Even if you type the same directly into the console you get the *bug* results. 

It seems to be due to the native `window.name` property which can only ever be a string so anything assigned to it has .toString() applied.

Using a different variable/const name other than 'name' gives the correct results, and so does wrapping it in a function.

**Comment by abhisekp** [comment] 2016-05-13 16:54
@r-murphy really? :flushed: 
thanks. Will try that and see. 

btw, wasn't the title really cachy :smirk:

**Comment by richgilbank** [comment] 2016-06-05 01:28
Thanks all, this does indeed seem to be from DevTools' variable scoping. Feel free to reopen if that's not the case though!

**Closed by richgilbank** 2016-06-05 01:28 UTC
